// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231209154916_SeedAnimals")]
    partial class SeedAnimals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Models.Bird", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Birds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01859fba-5ba5-46ac-8ca9-d5d3d46cacf4"),
                            LikesToPlay = true,
                            Name = "Alex"
                        },
                        new
                        {
                            Id = new Guid("35bf024b-c32e-4b31-a6e2-c0e380cc9687"),
                            LikesToPlay = true,
                            Name = "Sofia"
                        },
                        new
                        {
                            Id = new Guid("febb0644-b1a1-4a00-8475-031de8c804db"),
                            LikesToPlay = true,
                            Name = "Max"
                        },
                        new
                        {
                            Id = new Guid("12345678-1234-5678-1234-567812345670"),
                            LikesToPlay = true,
                            Name = "TestCatForUnitTests"
                        },
                        new
                        {
                            Id = new Guid("12345678-1234-5678-1234-567812345671"),
                            LikesToPlay = true,
                            Name = "TestCatForUnitTests"
                        },
                        new
                        {
                            Id = new Guid("12345678-1234-5678-1234-567812345678"),
                            LikesToPlay = true,
                            Name = "TestCatForUnitTests"
                        });
                });

            modelBuilder.Entity("Domain.Models.Cat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("832b4c46-0526-427f-a5b4-6abc7da249a8"),
                            LikesToPlay = true,
                            Name = "Steven"
                        },
                        new
                        {
                            Id = new Guid("4e4d7f8d-3a40-406c-86d3-c6bd8ecf1409"),
                            LikesToPlay = true,
                            Name = "Alpin"
                        },
                        new
                        {
                            Id = new Guid("2a3afce9-9b7a-4f9f-a35a-70696d102b75"),
                            LikesToPlay = true,
                            Name = "Nelson"
                        },
                        new
                        {
                            Id = new Guid("12345678-1234-5678-1234-567812345670"),
                            LikesToPlay = true,
                            Name = "TestCatForUnitTests"
                        },
                        new
                        {
                            Id = new Guid("12345678-1234-5678-1234-567812345671"),
                            LikesToPlay = true,
                            Name = "TestCatForUnitTests"
                        },
                        new
                        {
                            Id = new Guid("12345678-1234-5678-1234-567812345678"),
                            LikesToPlay = true,
                            Name = "TestCatForUnitTests"
                        });
                });

            modelBuilder.Entity("Domain.Models.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("08ed2ab4-1e22-4278-b388-b20a467b2b7a"),
                            LikesToPlay = true,
                            Name = "Björn"
                        },
                        new
                        {
                            Id = new Guid("d8626e6f-b081-4e5a-bad0-31ef15ffe272"),
                            LikesToPlay = true,
                            Name = "Patrik"
                        },
                        new
                        {
                            Id = new Guid("586f8b42-7222-4afd-a9aa-fcfe2e22740c"),
                            LikesToPlay = true,
                            Name = "Alfred"
                        },
                        new
                        {
                            Id = new Guid("12345678-1234-5678-1234-567812345670"),
                            LikesToPlay = true,
                            Name = "TestDogForUnitTests"
                        },
                        new
                        {
                            Id = new Guid("12345678-1234-5678-1234-567812345671"),
                            LikesToPlay = true,
                            Name = "TestDogForUnitTests"
                        },
                        new
                        {
                            Id = new Guid("12345678-1234-5678-1234-567812345678"),
                            LikesToPlay = true,
                            Name = "TestDogForUnitTests"
                        });
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
